import "~/styles/globals.css";

import { headers } from "next/headers";
import { Inter } from "next/font/google";
import { TRPCReactProvider } from "~/trpc/react";

import { AnimateEnter } from "./_components/animate-enter";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`font-sans ${inter.variable}`}>
        <TRPCReactProvider headers={headers()}>
          <AnimateEnter className="max-w-9xl mx-auto flex flex-col px-8 lg:flex-row lg:gap-10 lg:py-20">
            {children}
          </AnimateEnter>
        </TRPCReactProvider>
      </body>
    </html>
  );
}
